### ISSUE TITLE
Linting has already been configured. Please ensure that the call to `register_linters` is included as early as possible in your WORKSPACE.

### ISSUE THREAD

**Issue by bonigarcia** [apple/apple_rules_lint#6]
I'm trying to migrate the test codebase of the Selenium project to JUnit 5 ([issue #10196](https://github.com/SeleniumHQ/selenium/issues/10196)). Bazel does not support JUnit 5 yet, but it seems the [bazel-contrib/rules_jvm rules](https://github.com/bazel-contrib/rules_jvm) could do the trick. I made the following changes in the Bazel setup of Selenium to use these rules:

https://github.com/bonigarcia/selenium/commit/58c94fc26bcd4485bd0aae0ff97f754b79b8fff5

But when I try to build the project, I get the following error:

```
boni@slimbook:~/dev/selenium$ bazel build java/...
ERROR: Traceback (most recent call last):
	File "/home/boni/dev/selenium/WORKSPACE", line 80, column 11, in <toplevel>
		lint_setup({
	File "/home/boni/.cache/bazel/_bazel_boni/9e7fe06a1a741c30384ec144b4d06379/external/apple_rules_lint/lint/setup.bzl", line 61, column 13, in lint_setup
		fail(
Error in fail: Linting has already been configured. Please ensure that the call to `register_linters` is included as early as possible in your WORKSPACE. If you experience problems or need help, please raise an issue at https://github.com/apple/apple_rules_lint/issues/new
ERROR: error loading package '': Encountered error while reading extension file 'python/repositories.bzl': no such package '@rules_python//python': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.832s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Am I doing something wrong?

Thanks in advance.

**Comment by shs96c** [comment]
The error message says that you need to load `register_linters` before the other rulesets. I'd suggest loading `apple_rules_lint` before anything else in the `WORKSPACE` file, as Selenium does now.
